name=EM4095Reader
version=0.1.0
maintainer=Matthieu Matsima <matthieu.matsima@gmail.com>
author=Matthieu Matsima <matthieu.matsima@gmail.com>
sentence=Driver for the EM4095 to read RFID tags using FDX-B protocol
paragraph=
category=Communication
url=https://github.com/Matth-M/EM4095-Arduino
architectures=*
