name=EM4095_FDXB
version=0.1.0
maintainer=Matthieu Matsima <matthieu.matsima@gmail.com>
sentence=Driver for the EM4095 to read RFID tags using FDX-B protocol
category=Communication
url=https://github.com/Matth-M/EM4095-FDXB-Arduino
architectures=*
