name=EM4095
version=0.1.0
maintainer=Matthieu Matsima <matthieu.matsima@gmail.com>
sentence=Driver for the EM4095 to read RFID tags using FDX-B protocol
category=Communication
url=https://example.com/EM4095
architectures=*
